version: '3'
services:
  car-service:
    build: ./car-service
    ports:
      - "8090:8090"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaa:8761/eureka/
    depends_on:
      db:
        condition: service_healthy



  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: bazaTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./bazaTest:/data/postgres
    expose:
      - 5432
    ports:
      - '5438:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready","-d","bazaTest", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      eurekaa:
        condition: service_started


  config-server:
    build: ./config-server
    ports:
      - "8888:8888"




  eurekaa:
    build: ./eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: "exit 0"
    depends_on:
      config-server:
        condition: service_started



  gateway:
    build: ./gateway
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaa:8761/eureka/
    links:
      - car-service
    depends_on:
      eurekaa:
        condition: service_healthy
      car-service:
        condition: service_started


