version: '3'
services:
  ##Car-Service
  car-service:
    build: ./car-service
    ports:
      - "8090:8090"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry-eureka:8761/eureka/
      - eureka.instance.hostname=localhost
    depends_on:
      - "db-postgres"



  ##Postgres
  db-postgres:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_DB: bazaTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./bazaTest:/data/postgres
    expose:
      - "5432"
    ports:
      - "5438:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready","-d","bazaTest", "-U", "postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    command: -p 5432
    restart: always


  ##Config
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"



  ##Eureka
  registry-eureka:
    build: ./eureka
    ports:
      - "8761:8761"
#    healthcheck:
#      test: "exit 0"
#    depends_on:
#      config-server:
#        condition: service_started


  ##Gateway
  gateway:
    build: ./gateway
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry-eureka:8761/eureka/
      - eureka.instance.hostname=localhost


    links:
      - "car-service"
    depends_on:
      - "car-service"



