server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/**
        - id: car-service-2
          uri: lb://car-service-2
          predicates:
            - Path=/**
      loadbalancer:
        ribbon:
          enabled: false

