server:
  port: ${PORT:0}

spring:
  application:
    name: car-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
#  data:
#    postgres:
#      host: localhost
#      port: 5432
#      username: postgres
#      password: postgres
#      database: bazaTest
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://host.docker.internal:5438/bazaTest
#    url: jdbc:postgresql://localhost:5432/bazaTest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ribbon:
      listOfServers: http://localhost:8090
